name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Type check (optional - will not fail build)
        run: npx tsc --noEmit || true
        continue-on-error: true
        
      - name: Build Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_RAZORPAY_KEY_ID: rzp_live_28uKBwwEso0CLe
          NEXT_PUBLIC_RP_KEY_SECRET: KCXlmLuXdWl4Gb8MK475F56S
          NEXT_PUBLIC_BASE_URL_API: https://indi-landing-backend-xzzi7.ondigitalocean.app/
          NEXT_DISABLE_ESLINT: true
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4